app/employees/models.py
import re
from flask_babel import gettext as _
from app import db


class Employee(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(20), nullable=False,
                     info={'label': _('Name')})
    surname = db.Column(db.String(20), nullable=False,
                        info={'label': _('Surname')})
    email = db.Column(db.String(30),
                      info={'label': _('Email')})
    phone = db.Column(db.String(20),
                      info={'label': _('Phone')})
    birth_date = db.Column(db.Date, nullable=True,
                           info={'label': _('Birth date')})

    @db.validates('email')
    def validate_email(self, key, address):
        if not re.match(r'[^@]+@[^@]+\.[^@]+', address):
            raise ValueError(_('Invalid email'))
        return address

    @db.validates('phone_number')
    def validate_phone(self, key, phone):
        if not re.match(r'^(\s*)?(\+)?([- _():=+]?\d[- _():=+]?){10,14}(\s*)?$', phone):
            raise ValueError(_('Invalid phone number'))
        return phone

app/employees/forms.py
from wtforms import validators
from wtforms.fields.html5 import EmailField
from wtforms.fields.core import StringField
from flask_babel import gettext as _
from app.base.forms import ModelForm
from .models import Employee


class EmployeeForm(ModelForm):
    class Meta:
        model = Employee

    email = EmailField(_('Email'), [validators.DataRequired(), validators.Email()])
    phone = StringField(_('Phone'), [validators.DataRequired(),
                                     validators.Regexp('^(\s*)?(\+)?([- _():=+]?\d[- _():=+]?){10,14}(\s*)?$',
                                                       message=_('Invalid phone number'))])

app/employees/__init__.py
from .views import employees

app/employees/views.py
from datetime import date
from flask import Blueprint, url_for, redirect, flash
from flask_babel import gettext as _
from app.base.generic_views import ListView, DetailView, CreateView, EditView
from app import db
from .models import Employee
from .forms import EmployeeForm

employees = Blueprint('employees', __name__)


class EmployeeListView(ListView):
    template_name = 'employees/list.html'

    def get_queryset(self):
        return Employee.query.all()


class EmployeeDetailView(DetailView):
    model = Employee
    template_name = 'employees/detail.html'


class EmployeeCreateView(CreateView):
    model = Employee
    form_class = EmployeeForm
    template_name = 'employees/create.html'
    success_flash_message = _('Successfully created new employee.')

    def get_success_redirect_url(self):
        return url_for('employees.list')


class EmployeeEditView(EditView):
    model = Employee
    form_class = EmployeeForm
    template_name = 'employees/edit.html'
    success_flash_message = _('Successfully edited.')

    def get_success_redirect_url(self):
        return url_for('employees.detail',
                       pk=self.object.id)


@employees.route('/<int:pk>/fire', methods=['POST'])
def fire(pk):
    # close all employees positions
    employee = Employee.query.get_or_404(pk)
    today = date.today()
    for position in employee.positions:
        if position.leave_date is None:
            position.leave_date = today

    db.session.commit()
    flash(_('Successfully fired an employee.'))
    return redirect(url_for('employees.detail', pk=employee.id))


employees.add_url_rule('/', view_func=EmployeeListView.as_view('list'))

employees.add_url_rule('/<int:pk>',
                       view_func=EmployeeDetailView.as_view('detail'))

employees.add_url_rule('/create',
                       view_func=EmployeeCreateView.as_view('create'))

employees.add_url_rule('/<int:pk>/edit',
                       view_func=EmployeeEditView.as_view('edit'))

app/templates/employees/_employees_table.html
{% macro employees_table(employees) %}
<div class="row">
    <table id="employees-table" class="table table-bordered">
        <thead>
            <tr>
                <th>{{ _('Name') }}</th>
                <th>{{ _('Department') }}</th>
                <th>{{ _('Position') }}</th>
                <th>{{ _('Is head') }}</th>
                <th>{{ _('Email') }}</th>
                <th>{{ _('Phone') }}</th>
                <th>{{ _('Is fired') }}</th>
                <th>{{ _('Detail') }}</th>
            </tr>
        </thead>
        <tbody>
            {% for employee in employees %}
                <tr>
                    <td><p>{{ employee.name }} {{ employee.surname }}</p></td>
                    {% if employee.positions %}
                        <td><p>{{ employee.positions[-1].department.name }}</p></td>
                        <td><p>{{ employee.positions[-1].typical_position.name }}</p></td>
                        <td><p>{% if employee.positions[-1].is_head %}{{ _('Head') }}{% endif %}</p></td>
                    {% else %}
                        <td></td>
                        <td></td>
                        <td></td>
                    {% endif %}
                    <td><p>{{ employee.email }}</p></td>
                    <td><p>{{ employee.phone }}</p></td>
                    {% if employee.positions %}
                        <td><p>{% if employee.positions[-1].leave_date %}{{ _('Fired') }}{% endif %}</p></td>
                    {% else %}
                        <td></td>
                    {% endif %}
                    <td><a href="{{ url_for('employees.detail', pk=employee.id) }}">{{ _('Detail') }}</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endmacro %}

app/templates/employees/create.html
{% extends 'base.html' %}

{% from '_render_field.html' import render_field %}

{% block title %}
    {{ _('Create employee') }}
{% endblock %}

{% block content %}
    <div class="row">
        <ol class="breadcrumb">
            <li><a href="{{ url_for('employees.list') }}">{{ _('Employees') }}</a></li>
            <li class="active">{{ _('Create') }}</li>
        </ol>
    </div>

        <div class="col-xs-4 col-xs-offset-4">
            <form action="{{ url_for('employees.create') }}" method="POST">
                {{ form.hidden_tag() }}
                <h2 class="text">{{ _('Create employee') }}</h2>
                <dl>
                    {% for field in form if field.widget.input_type != 'hidden' %}
                        {{ render_field(field) }}
                    {% endfor %}
                </dl>
                <button class="btn btn-small btn-success btn-block" type="submit">{{ _('Create') }}</button>
            </form>
        </div>
{% endblock %}

app/templates/employees/detail.html
{% extends 'base.html' %}

{% from 'positions/_positions_table.html' import positions_table %}

{% block title %}
    {{ object.name }} {{ object.surname }}
{% endblock %}

{% block extra_js %}
    <script src="{{ url_for('static', filename='js/plugins/jquery-3.1.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/plugins/datatables.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/positions/positions_table.js') }}"></script>
    <script type="text/javascript">
        var url = '{{ url_for('employees.fire', pk=object.id) }}';
        $('#fire-button').click(function() {
            $.post(url, function () {
                location.reload();
            });
        });
    </script>
{% endblock %}

{% block content %}
    <div class="row">
        <ol class="breadcrumb">
            <li><a href="{{ url_for('employees.list') }}">{{ _('Employees') }}</a></li>
            <li class="active">{{ object.name }} {{ object.surname }}</li>
        </ol>
    </div>
    <div class="row">
        <h1 class="text">{{ object.name }} {{ object.surname }}</h1>
        <p class="text">{{ _('Birth date') }}: {{ object.birth_date }}</p>
        <p class="text">{{ _('Email') }}: {{ object.email }}</p>
        <p class="text">{{ _('Phone') }}: {{ object.phone }}</p>
        <button class="btn btn-danger" id="fire-button">{{ _('Fire employee') }}</button>
        <a class="btn btn-default" href="{{ url_for('employees.edit', pk=object.id) }}">{{ _('Edit') }}</a>
{#        <a class="btn btn-danger" href="{{ url_for('employees.delete') }}">{{ _('Delete') }}</a>#}
    </div>
    <hr>
    {% if object.positions %}
        <div class="row">
            <h2 class="text">
                {{ _('Positions placed') }}:
            </h2>
        </div>
        {{ positions_table(object.positions | reverse) }}
    {% else %}
        <div class="row">
            <h2 class="text">{{ _('No positions yet') }}</h2>
        </div>
    {% endif %}
{% endblock %}

app/templates/employees/edit.html
{% extends 'base.html' %}

{% from '_render_field.html' import render_field %}

{% block title %}
    {{ _('Edit employee') }}
{% endblock %}

{% block content %}
    <div class="row">
        <ol class="breadcrumb">
            <li><a href="{{ url_for('employees.list') }}">{{ _('Employees') }}</a></li>
            <li><a href="{{ url_for('employees.detail', pk=object.id) }}">{{ object.name }}</a></li>
            <li class="active">{{ _('Edit') }}</li>
        </ol>
    </div>
    <div class="col-xs-4 col-xs-offset-4">
        <form action="{{ url_for('employees.edit', pk=object.id) }}" method="POST">
            {{ form.hidden_tag() }}
            <h2 class="text">{{ _('Edit employee') }}</h2>
            <dl>
                {% for field in form if field.widget.input_type != 'hidden' %}
                    {{ render_field(field) }}
                {% endfor %}
            </dl>
            <button class="btn btn-small btn-primary btn-block" type="submit">{{ _('Edit') }}</button>
        </form>
    </div>
{% endblock %}

app/templates/employees/list.html
{% extends 'base.html' %}

{% from 'employees/_employees_table.html' import employees_table %}

{% block title %}
    {{ _('Employees list') }}
{% endblock %}

{% block extra_js %}
    <script src="{{ url_for('static', filename='js/plugins/jquery-3.1.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/plugins/datatables.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/employees/employees_table.js') }}"></script>
{% endblock %}

{% block content %}
    <div class="row">
        <h1 class="text">{{ _('All employees') }}</h1>
    </div>
    {% if objects %}
        {{ employees_table(objects) }}
    {% else %}
        <div class="row">
            <h3 class="text">{{ _('No employees yet.') }}</h3>
        </div>
    {% endif %}
    <div class="row">
        <a class="btn btn-success" href="{{ url_for('employees.create') }}">{{ _('Create Employee') }}</a>
    </div>
{% endblock %}